### PR TITLE
gopkg v0.1.1

### PR DESCRIPTION
**Pull request by kuritka**
In order to breaking change in controller-runtime v0.8.3 I decided to:
 - remove `controller` package (temporarly)
 - fix documentation

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
It's not clear to me:

* What we are losing by removing the `controller` package
* If documentation fixes are anyhow related to the problem
* Why `go.mod` was downloading the Internet before this change

**Comment by kuritka** [comment]
The problem is module `sigs.k8s.io/controller-runtime v0.8.3` which has many dependencies. That's why `go.sum` grew into giant dimension. We lost nothing as v0.1.0 was not used yet. Also controller was moved from k8gb here, but it can stay where it is (https://github.com/AbsaOSS/k8gb/blob/master/controllers/internal/utils/reconciler_result.go).

The whole problem is, that k8gb uses `sigs.k8s.io/controller-runtime` version A while gopkg uses `sigs.k8s.io/controller-runtime` version B. Which is not blocker but package tree behind `sigs.k8s.io/controller-runtime` is so large that it can't simply cooperate together without `replaces`, `exclude` etc in `go.mod`.

**Review by ytsarev — APPROVED** [review]
Thanks for the clarifications.

I need to think it through but in general I wouldn't move the code related to Reconciliation outside of k8gb controller

**Comment by kuritka** [comment]
@ytsarev, yes that's true. I was thinking a lot if I should move this part or not. Basically, it's just a helper. Maybe it is better if this concrete helper stays in k8gb

**Pull request merged**
